project:
  type: website
  output-dir: docs
  resources:
    - "test.html"

website:
  title: "Example dashboard"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - test-js.qmd
      - test.html
      - new_comments_example.qmd

format:
  html:
    theme: cosmo
    toc: true
    comments:
      utterances:
         repo: murphyqm/testing-utterances



