[project]
authors = ["Maeve Murphy Quinlan <earmmu@leeds.ac.uk>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "example-dashboard"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.2,<3.14"
matplotlib = ">=3.10.1,<3.11"
seaborn = ">=0.13.2,<0.14"
bokeh = ">=3.7.0,<3.8"
plotly = ">=6.0.1,<6.1"
jupyter = ">=1.1.1,<1.2"
ipyleaflet = ">=0.19.2,<0.20"
folium = ">=0.19.5,<0.20"
geopandas = ">=1.0.1,<2"
htmltools = ">=0.6.0,<0.7"
h3-py = ">=4.2.2,<5"
tabulate = ">=0.9.0,<0.10"
itables = ">=2.2.5,<3"
